Description: >
  Adcuratio
  This template deploys a EC2 instance with a security group
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
  S3CodeBucketName:
    Description: >-
      The name of the S3 bucket containing the zipped application code 
      to be deployed
    Type: String
    AllowedPattern: ^[0-9a-zA-Z][0-9a-zA-Z-]*$
  S3CodeArchive:
    Description: The application code archive (must end with .zip)
    Type: String
    AllowedPattern: ^.*\.zip$

Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 23750
          ToPort: 23750
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9000
          ToPort: 9000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8090
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8001
          ToPort: 8001
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 2376
          ToPort: 2376
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 23750
          ToPort: 23750
          CidrIpv6: ::/0
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          CidrIpv6: ::/0
        - IpProtocol: tcp
          FromPort: 8001
          ToPort: 8001
          CidrIpv6: ::/0
        - IpProtocol: tcp
          FromPort: 2376
          ToPort: 2376
          CidrIpv6: ::/0
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-04feaf10b86d509a2 # Adcuratio custom (N. Virginia)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          # Install Apache 2
          apt-get update -y
          apt-get install unzip awscli -y
          apt-get install apache2 -y
          systemctl start apache2.service
          cd /var/www/html
          # Copy the web application archive
          aws s3 cp s3://${S3CodeBucketName}/${S3CodeArchive} .
          # unzip the archive
          unzip -o ${S3CodeArchive}
      Tags:
        - Key: Name
          Value: My EC2 Instance
        - Key: Type
          Value: Server Instance

  S3CodeBucketCopyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: /

  RootInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - !Ref S3CodeBucketCopyRole

  S3CodeBucketCopyPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3CodeBucketCopyPolicy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
            Resource: "*"
      Roles:
        - !Ref S3CodeBucketCopyRole
