Description: >
  Adcuratio
  This template deploys a EC2 instance with a security group
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
Resources:
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId:
        Fn::ImportValue: !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 23750
          ToPort: 23750
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9000
          ToPort: 9000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8090
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8001
          ToPort: 8001
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 2376
          ToPort: 2376
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 23750
          ToPort: 23750
          CidrIpv6: ::/0
        - IpProtocol: tcp
          FromPort: 27017
          ToPort: 27017
          CidrIpv6: ::/0
        - IpProtocol: tcp
          FromPort: 8001
          ToPort: 8001
          CidrIpv6: ::/0
        - IpProtocol: tcp
          FromPort: 2376
          ToPort: 2376
          CidrIpv6: ::/0
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0f0037f3389122041 # Adcuratio custom (N. Virginia)
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum -y update

          # install apache
          yum install httpd24 -y  

          # start server
          service httpd start
          chkconfig httpd on
      Tags:
        - Key: Name
          Value: My EC2 Instance
        - Key: Type
          Value: Server Instance
